apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
      {{#each host}}
        - host: "{{this}}"
      {{/each}}
      rules: []
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        name: tokendings-postgres
        databases:
          - name: tokendings
            envVarPrefix: DB

  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}

  env:
  {{#each env}}
    - name: "{{@key}}"
      value: "{{this}}"
  {{/each}}

  envFrom:
    - secret: {{app}}-bearerauth
    - secret: {{app}}-private-jwks
