app: tokendings
namespace: plattformsikkerhet
team: plattformsikkerhet
ingresses:
  - https://tokendings.prod-gcp.nais.io
host:
  - oidc.difi.no
env:
  APPLICATION_PROFILE: PROD
slack_alert_channel: "plattformsikkerhet-alerts-prod"
