name: detekt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  detekt:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Detekt Codesmell
        uses: natiginfo/action-detekt-all@1.15.0
        with:
          args: >
            -r sarif:reports/detekt.json
            --jvm-target 14
            --build-upon-default-config
            --config detekt/detekt-config.yml
      - name: Detekt tests results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: detekt-results
          path: reports/detekt.json
